# SearXNG settings

use_default_settings: true

general:
  debug: false
  instance_name: "SearXNG Search API"

search:
  safe_search: 0
  formats:
    - html
    - json

server:
  secret_key: "changeme_secretkey_for_production"
  limiter: false
  image_proxy: true
